### PR TITLE
Implement CorrectionEngine interfaces

### LINKED ISSUE #68: Interfaces for CorrectionEngine
Implements the proposed interfaces for #9

### PR DESCRIPTION
**Pull request by kevinputera**
Closes #68 

This PR implements the interfaces useful for the implementation of the `CorrectionEngine` logic.
As discussed in #9, I'm implementing 3 interfaces/enums: `CorrectionEngine`, `CorrectionResult`, and `CorrectionStatus`.

@johannagwan @firzanarmani @ljiazh3ng please help me check this out!

### CODE REVIEW

**Review by ljiazh3ng — APPROVED** [review]
LGTM

**Review by johannagwan — APPROVED** [review]
LGTM too! Thanks Kevin!

**Review by firzanarmani — APPROVED** [review]
LGTM for me too!

**Comment by kevinputera** [comment]
@johannagwan @ljiazh3ng @firzanarmani alright thanks guys! i'll merge this in once #44 is reverted

**Pull request merged**
