### PR TITLE
Removed dependencies related with deleting Person model

### LINKED ISSUE #47: Remove/change dependencies related with deleting Person model.
Classes that are dependent on Person are:
- Logic.Command
- Logic.Parser
- Storage

### PR DESCRIPTION
**Pull request by ljiazh3ng**
Closes #47 

Some of the dependencies include:

- TestCases

- Logic/Commands

- AddressBook

### CODE REVIEW

**Review by firzanarmani — COMMENTED** [review]
Hi @ljiazh3ng, please look through these first while I look through the rest of the changes
- [x] Commit messages should be in present tense
- [x] There's a typo in the commit message f35e65a0c38b19363dfadf526194a307fdca0991
- [x] Please merge latest changes from upstream

**Comment by kevinputera** [comment]
@HemanshuGandhi please help review this too when you have time! There are some UI changes involved in this PR

**Comment by ljiazh3ng** [comment]
Thanks you @firzanarmani  and @kevinputera , i've made the necessary changes, removed all dependencies related to Person class. Please let me know if there are anymore problems.

**Comment by firzanarmani** [comment]
@ljiazh3ng Your latest commit message is not in imperative form. Also, the intention of the commit is to point out the change, rather than the build passing (what if it didn't, for some reason). I would suggest renaming it to something like "Comment out broken tests to fix build test"

@kevinputera I think these changes are enough to move forward with passing build checks and proceed with the larger refactoring.
Though, as previously discussed, at first we thought of commenting out methods that broke because of the removal of Person and its dependencies. However, leaving it as returning `void` or `Object` for certain methods save us some time for now, and allow us to just carry on with the larger task of refactoring everything else. What's your opinion?

**Comment by kevinputera** [comment]
> @ljiazh3ng Your latest commit message is not in imperative form. Also, the intention of the commit is to point out the change, rather than the build passing (what if it didn't, for some reason). I would suggest renaming it to something like "Comment out broken tests to fix build test"
> 
> @kevinputera I think these changes are enough to move forward with passing build checks and proceed with the larger refactoring.
> Though, as previously discussed, at first we thought of commenting out methods that broke because of the removal of Person and its dependencies. However, leaving it as returning `void` or `Object` for certain methods save us some time for now, and allow us to just carry on with the larger task of refactoring everything else. What's your opinion?

Hey @ljiazh3ng @firzanarmani thanks a lot for this! Yes, I agree with y'all, let's just stick with the bare minimum change needed to allow others to test out their parts.

However, as it turns out, we cannot run the application now (`./gradlew run`) due to some NPE. Let me take a look at this and get back to you

**Comment by kevinputera** [comment]
Hey @ljiazh3ng @firzanarmani! I pushed a commit where I removed the `PersonList` and `PersonCard` views from our app's UI. This should do the work for now. Do try `./gradlew run` now, it should work!

Let's merge this in once you all take a look!

**Comment by kevinputera** [comment]
@HemanshuGandhi Hey Hemanshu! Could you help us check this PR out and try running it locally too? See if everything's fine from your side. In short, from UI's perspective, the followings are removed:
1. The `PersonCardList` fxml and java class
2. The `PersonListPanel` fxml and java class

**Comment by HemanshuGandhi** [comment]
@kevinputera I have tested the pr locally, and on my end, the build is working. No checkstyle errors or any runtime errors.

**Review by HemanshuGandhi — APPROVED** [review]

**Pull request merged**
