### PR TITLE
Remove CommandResult

### LINKED ISSUE #21: Remove CommandResult.java
logic --> commands --> CommandResult.java
NOTE: we will be using Observables

### PR DESCRIPTION
**Pull request by firzanarmani**
Resolves #21

### CODE REVIEW

**Comment by kevinputera** [comment]
@firzanarmani "Solves" is not one of the [special keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) for linking to an issue!

**Review by kevinputera — COMMENTED** [review]
Looks good!

**Comment by firzanarmani** [comment]
> @firzanarmani "Solves" is not one of the [special keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) for linking to an issue!

Edited PR comment accordingly! Thanks for pointing it out @kevinputera

**Review by ljiazh3ng — APPROVED** [review]
LGTM

**Pull request merged**
