### PR TITLE
Remove redundant classes for Model, Storage and CommandResult

### LINKED ISSUE #21: Remove CommandResult.java
logic --> commands --> CommandResult.java
NOTE: we will be using Observables

### LINKED ISSUE #26: Remove redundant classes for Model
Such classes include "Person", "Name", "Tag", etc. Remove the classes that seem redundant in order to achieve milestone v1.1

### LINKED ISSUE #27: Remove redundant classes for Storage
Remove JsonAddressBook class and its dependents.

### PR DESCRIPTION
**Pull request by firzanarmani**
1. Remove CommandResult class (Resolves #21)
2. Remove Person model and its dependent model classes (Resolves #26)
3. Remove AddressBook and other dependent Storage classes (Resolves #27)

More code refactoring and cleanup needs to be done all around the codebase as a result of these removals.

### CODE REVIEW

**Review by kevinputera — APPROVED** [review]
LGTM! Here are a few considerations:

1. Should we create an issue where you remove all the other classes' dependency from these deleted classes? For example, `ModelManager` currently uses the `AddressBook` class.
2. I think you should create an issue around removing the test cases of these deleted classes, before merging this PR in. Otherwise, our current test suite will definitely fail.
3. This just came across my mind. I believe you should rename `ReadOnlyAddressBook` to something else that is more relatable to our use case. Should we do this in another issue?
4. Lastly, I'm curious about why you chose not to delete the `Tag` class and the `seedu.address.model.person` package wholly. Are there any reasons for that?

**Comment by kevinputera** [comment]
Oh yes, let's add the `status.onGoing` tag to each of the issues this PR is solving. I have added them to the issues related to this PR, so this is just for future reference.

In addition, let's [link](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) the issues this PR resolves so that they are automatically closed when this PR is merged in.

**Comment by ljiazh3ng** [comment]
> LGTM! Here are a few considerations:
> 
> 1. Should we create an issue where you remove all the other classes' dependency from these deleted classes? For example, `ModelManager` currently uses the `AddressBook` class.
> 2. I think you should create an issue around removing the test cases of these deleted classes, before merging this PR in. Otherwise, our current test suite will definitely fail.
> 3. This just came across my mind. I believe you should rename `ReadOnlyAddressBook` to something else that is more relatable to our use case. Should we do this in another issue?
> 4. Lastly, I'm curious about why you chose not to delete the `Tag` class and the `seedu.address.model.person` package wholly. Are there any reasons for that?

Thank for reviewing the PR. I'll also like to answer your suggestions in parts below.

> 1. Yes i think we should create issue for the other classes that were dependent on the current classes removed. We could tag it under 1.2 ?
> 2. Will we still be using any of their test cases? Should create a new issue for  "Creating new test cases" ?
> 3. Oh yes, we were planning to do that. Will commit that for our next PR.
> 4. We missed out that part, it was unstaged in the commit. Thanks for noticing.

**Comment by kevinputera** [comment]
> 1. Yes i think we should create issue for the other classes that were dependent on the current classes removed. We could tag it under 1.2 ?

How about we tag it under v1.15, since they kinda serve the same purpose (not like other feature implementation tasks for v1.2)

> 2. Will we still be using any of their test cases? Should create a new issue for  "Creating new test cases" ?

I'd suggest that we remove all the current test cases related to the class being tested. If needed, we can create a new issue in the future specifically for implementing tests, once the features have been implemented.

> 3. Oh yes, we were planning to do that. Will commit that for our next PR.

Alright 👍
As a suggestion, try to create your PRs based on a coherent set of tasks/functionality. It need not be too big, as long as it is, in a way, a coherent unit (e.g. an epic can be split into multiple user stories that can be implemented in separate PRs)

> 4. We missed out that part, it was unstaged in the commit. Thanks for noticing.

Alright 👍
Please push it in whenever you're ready!

Let's merge this in at least after tomorrow's tutorial (let's also relax the CI rigor since we're making many big changes) so that this PR does not affect our grading for v1.1

**Comment by firzanarmani** [comment]
Pull request closed in favour of properly splitting the commit changes between @firzanarmani and @ljiazh3ng to separate pull requests.

**Pull request closed without merging**
