### PR TITLE
Remove unused CI config

### LINKED ISSUE #65: Remove unused CI/CD integration
Remove integration for:
- AppVeyor
- Coveralls

### PR DESCRIPTION
**Pull request by firzanarmani**
Resolves #65 

1. Remove AppVeyor configuration file
2. Remove JaCoCo code coverage plugin and script
3. Remove Coveralls integration (with JaCoCo plugin)

Need your advice @kevinputera

### CODE REVIEW

**Review by kevinputera — APPROVED** [review]
Looks great!

**Comment by firzanarmani** [comment]
Will put merge on hold until #44 is reverted accordingly

**Comment by firzanarmani** [comment]
Force pushed to 2936afd to fix typo in commit message

**Comment by firzanarmani** [comment]
Force pushed latest upstream master merge

**Pull request merged**
