### PR TITLE
Remove FindCommand and its relevant usages/ references

### LINKED ISSUE #24: Rename FindCommand.java to SearchCommand.java
logic --> commands --> FindCommand.java

### LINKED ISSUE #74: Remove FindCommand class
We will integrate the Search function into our SuggestionEngine, thus there is no need of a FindCommand class.

To remove:
- FindCommand.java
- FindCommandParser.java
- FindCommandTest.java
- FindCommandParserTest.java
and their relevant usages/ references.

### PR DESCRIPTION
**Pull request by johannagwan**
EDIT: Remove link to issue #24. 

Resolves #74.

Removed:
- FindCommand.java
- FindCommandParser.java
- FindCommandTest.java
- FindCommandParserTest.java
and their relevant usages/ references.

### CODE REVIEW

**Comment by kevinputera** [comment]
> Resolves #24 and #74.
> 
> Removed:
> 
> * FindCommand.java
> * FindCommandParser.java
> * FindCommandTest.java
> * FindCommandParserTest.java
>   and their relevant usages/ references.

You shouldn't link to the issue #24! Instead, close that issue and remove it from the description of this PR since it is no longer relevant

In addition, it seems that github doesn't link this PR to the issue #74. Probably because you're using the 'and' keyword which is not understood by github. Do check this out and rectify accordingly

**Review by kevinputera — COMMENTED** [review]
Looks good to me!

**Comment by johannagwan** [comment]
Hi @kevinputera, thank you so much for the review! I have made the necessary edit to my PR. Thank you!

**Review by ljiazh3ng — APPROVED** [review]
LGTM

**Pull request merged**
